# Generated by Django 4.1.4 on 2023-01-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_cousre',
            new_name='stud_course',
        ),
    ]
